### ISSUE TITLE
Install on Ubuntu

### ISSUE THREAD

**Issue by auhorn** [projectkudu/KuduSync#22]
I am trying to install kudusync via ('sudo npm install kudusync -g') on Ubuntu 14.04 and get this error message.
`npm ERR! Error: ENOENT, chmod '/usr/local/lib/node_modules/kudusync/bin/kudusync'`.
node version is 0.10.25
npm version is 1.3.10

Please let me know if you need more information

**Comment by albertjan** [comment]
@amitapl this is resolved

**Comment by amitapl** [comment]
great thanks!
