### ISSUE TITLE
Is there any documentation for kudusync?

### ISSUE THREAD

**Issue by albertjan** [projectkudu/KuduSync#23]

**Comment by atrauzzi** [comment]
:+1:

**Comment by davidebbo** [comment]
Doesn't look like we have much, but it would be good to get at least basic command line documented on this wiki, or in readme.md.

@amitapl any chance you can describe the basics? Thanks!

**Comment by amitapl** [comment]
Sure




________________________________

**Comment by davidebbo** [comment]
Thanks Amit! To clarify, it's in the readme. https://github.com/projectkudu/KuduSync
