### ISSUE TITLE
Prevent generating iisnode.yml 

### ISSUE THREAD

**Issue by footmarks-skylar** [projectkudu/KuduSync#29]
Is there an option I can pass to kudosync to prevent it from generating the web.config and iisnode.yml defaults?

Our environments have static iisnode.yml and web.config files that are within the azure website root directory and not part of the git repo. Kudosync generates defaults for both files (since they are not part of the git) and replaces ours. 

Using Git deployment to remote from local and running default deploy.cmd

Thanks guys! I Love Kudu!

**Comment by davidebbo** [comment]
I don't think that KuduSync knows anything special about those files. Instead, I think that all happens in [selectNodeVersion.js](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Scripts/selectNodeVersion.js), which is part of Kudu.

**Comment by davidebbo** [comment]
BTW, not saying that the idea is not potentially interesting, but just that it's the wrong repo :)

**Comment by footmarks-skylar** [comment]
You're absolutely right. Thank you.
