### ISSUE TITLE
Support for wildcard entries in csproj

### ISSUE THREAD

**Issue by deevus** [projectkudu/KuduSync#32]
I have a directory `Assets/` that is generated at build time using `webpack`. It is defined in my `csproj` using the following:

```xml
  <ItemGroup>
    <Content Include="Assets\**\*" />
  </ItemGroup>
```

Can this be included in the kuduSync command?

**Comment by davidebbo** [comment]
I would think that his should just work. The default deployment script first runs msbuild to produce an artifact folder, and then copies everything in there using KuduSync. Kudu or KuduSync don't need to know anything about the wild cards.

**Comment by deevus** [comment]
I'll retest and get back to you.

**Comment by deevus** [comment]
You're correct, it does work. Thanks.
