### ISSUE TITLE
npm 5 symlinks local packages

### ISSUE THREAD

**Issue by cchamberlain** [projectkudu/KuduSync#33]
In testing out npm 5 on kudu I ran into some issues around a local npm package that we bundle in our git repo, and reference in `package.json` via `"file:../npm_packages/my-package"` paths. It looks like the new npm behavior is to symlink local packages instead of copy them. When running `npm install`, I noticed errors around symlinks and the local package (don't have the error text at the moment, but it was pretty clearly denying symlink creation due to privileges).

Found https://github.com/npm/npm/pull/15900 on the topic.

Any chance of adding some level of symlink support to allow npm 5 to work as intended?

**Comment by davidebbo** [comment]
The [sandbox](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox) used on App Service does not allow symlinks, and talking to experts, that is not likely to change. Does npm5 require them, or is there a way to turn that off?

**Comment by davidebbo** [comment]
Closing, since it really isn't KuduSync (or Kudu) related, but a general App Service thing.

**Comment by cchamberlain** [comment]
@davidebbo - All good, didn't find it likely to change just wanted to mention so that it would be on the radar. I'm not sure on workarounds yet but will leave a comment if I find one.

**Comment by davidebbo** [comment]
Thanks, please do follow up if you find workarounds.
